### PR TITLE
fix #88: i18n description confusion

### LINKED ISSUE #88: Description of question i18n not clear
The description/examples of this question could be more detailed, as `dog->d1g` is a valid case according to the description but failed here:

screen shot 2017-04-03 at 1 43 08 pm

Maybe like below:
An abbreviation of a word follows the form `<first character><length of the middle of the string><last character>`. Below are some examples of word abbreviations:
a) it                   --> it    (no abbreviation)
b) d|o|g            --> dog (no abbreviation)
c) i|nternationalizatio|n  --> i18n

### PR DESCRIPTION
**Pull request by jianjinjian**
Modified the original question description from 
" _returns an abbreviation of the string of the form `<first character><length of the middle of the string><last character>`._
 to
" _returns an abbreviation of the string of the form `<first character><length of the middle of the string><last character>` if it shortens the input._ "

### CODE REVIEW

File: assets/questions/i18n.js [hunk 1]
```diff
@@ -55,7 +55,8 @@ def are_all_unique(words):
       [
         'First, implement the abbreviate function. It takes a string as input ',
         'and returns an abbreviation of the string of the form ',
-        '<first character><length of the middle of the string><last character>. ',
+        '<first character><length of the middle of the string><last character> ',
+        'if it shortens the input. ',
```
Comment (seanlip) [inline assets/questions/i18n.js]: What do you think about saying: "but only if it shortens the input"?

Comment (jianjinjian) [inline assets/questions/i18n.js]: Yeah, sounds good, thx for the suggestion, this was added
